---
# This variable must be consistent with the 's3_audio_bucket' variable in terraform
s3_demo_audio:   this-project-media-prod
region:                 ap-southeast-2

# opensips value must be consistent with the host in route53.tf (terraform)
opensips:               opensips1.project.global
opensips2:              opensips2.project.global
opensips_webrtc_1:      opensips-webrtc1.project.global
opensips_webrtc_2:      opensips-webrtc2.project.global

wss_endpoint:           56a03aead6e8f7341bca7ca527c4794a.prod.project.thisglobal.net

uat: false
# Custom Dial Plan

exten_test_rule1:  |
      ;same => n,GotoIf($["${EXTEN}" = "998989898898"]?project-dev,${EXTEN},1)

exten_test_rule2: |
      ;[project-dev]
      ;exten => _[+0-9a-zA-Z]X.,1(start),Verbose(1, Inbound call: From ${CALLERID(num)} to ${EXTEN}|${SIP_HEADER(To)})
      ;same  => n,Stasis(bar,AU)
          